server:
  port: 8080

auth:
  type: "@auth.type@"

spring:
  security:
    oauth2:
      client:
        registration:
          my-cloud-hub-ui:
            # 這裡的 provider 名稱可以自訂，例如 'my-auth-provider'
            provider: my-auth-provider
            client-id: my-cloud-hub-ui
            # 使用占位符
            client-secret: "@client.secret@"
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile
        provider:
          my-auth-provider:
            # 使用占位符
            issuer-uri: "@issuer.uri@"
            # 完全禁用 UserInfo 端點
            user-info-uri: ""
            user-info-authentication-method: none

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.web: DEBUG
    com.example.mycloudhubui: DEBUG
