server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.web: DEBUG
    com.example.mycloudhubui: DEBUG
