spring:
  security:
    oauth2:
      client:
        registration:
          my-cloud-hub-ui:
            provider: auth-server
            client-id: my-cloud-hub-ui
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, read, write
        provider:
          auth-server:
            issuer-uri: http://127.0.0.1:9000